#dotenv: .env

paths:
  contracts: ./contracts
  sources: ./node_modules

dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.2
compiler:
  solc:
    version: "0.8.20"
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.2'

networks:
  #sepolia:
  #  host: "https://sepolia.infura.io/v3/WEB3_INFURA_PROJECT_ID"
  development:
    cmd: ganache-cli